export const quotes = [
    "“Music is like a dream. One that I cannot hear.” ―  Ludwig van Beethoven",
    "“Music gives a soul to the universe, wings to the mind, flight to the imagination and life to everything.” ― Plato",
    "“There are two means of refuge from the miseries of life: music and cats.” ― Albert Schweitzer",
    "“Music is the shorthand of emotion.” ― Leo Tolstoy",
    "“If music be the food of love, play on, Give me excess of it; that surfeiting, The appetite may sicken, and so die.” ― William Shakespeare",
    "“After silence, that which comes nearest to expressing the inexpressible is music.” ― Aldous Huxley",
    "“Where words fail, music speaks.” ― Hans Christian Andersen",
    "“Music expresses that which cannot be said and on which it is impossible to be silent.” ― Victor Hugo",
    "“We are the music makers, and we are the dreamers of dreams.” ― Arthur O’Shaughnessy",
    "“Music produces a kind of pleasure which human nature cannot do without.” ― Confucius",
    "“Music, once admitted to the soul, becomes a sort of spirit, and never dies.” ― Edward Bulwer-Lytton",
    "“A painter paints pictures on canvas. But musicians paint their pictures on silence.” ― Leopold Stokowski",
    "“Music . . . can name the unnameable and communicate the unknowable.” ― Leonard Bernstein",
    "“Music is the literature of the heart; it commences where speech ends.” ― Alphonse de Lamartine",
    "“The music is not in the notes, but in the silence between.”  ― Wolfgang Amadeus Mozart",
    "“Music makes one feel so romantic – at least it always gets on one’s nerves – which is the same thing nowadays.”― Oscar Wilde",
    "“Music is the strongest form of magic.” ― Marilyn Manson",
    "“Music is the wine that fills the cup of silence.” ― Robert Fripp",
    "“Music is the language of the spirit. It opens the secret of life bringing peace, abolishing strife.” ― Kahlil Gibran",
    "“Music in the soul can be heard by the universe.” ― Lao Tzu",
    "“Music acts like a magic key, to which the most tightly closed heart opens.” ― Maria Augusta von Trapp",
    "“Music… will help dissolve your perplexities and purify your character and sensibilities, and in time of care and sorrow, will keep a fountain of joy alive in you.” ― Dietrich Bonhoeffer",
    "“Music is an outburst of the soul.” ― Frederick Delius",
    "“Music produces a kind of pleasure which human nature cannot do without.” ― Confucius",
    "“It is always fatal to have music or poetry interrupted.” ― George Eliot",
    "“My heart, which is so full to overflowing, has often been solaced and refreshed by music when sick and weary.” ― Martin Luther",
    "“No matter how corrupt, greedy, and heartless our government, our corporations, our media, and our religious & charitable institutions may become, the music will still be wonderful.” ― Kurt Vonnegut",
    "“Life seems to go on without effort when I am filled with music.” ― George Eliot",
    "“Music is an agreeable harmony for the honor of God and the permissible delights of the soul.” ― Johann Sebastian Bach",
    "“If music be the food of love, play on.” ― William Shakespeare",
    "“I see my life in terms of music.” ― Albert Einstein",
    "“To me, the greatest pleasure of writing is not what it’s about, but the music the words make.” ― Truman Capote",
    "“Musical innovation is full of danger to the State, for when modes of music change, the fundamental laws of the State always change with them.” ― Plato",
    "“Music could ache and hurt, that beautiful music was a place a suffering man could hide.” ― Pat Conroy",
    "“If I cannot fly, let me sing.” ― Stephen Sondheim",
    "“Music brings a warm glow to my vision, thawing mind and muscle from their endless wintering.” ― Haruki Murakami",
    "“Most people die with their music still locked up inside them.” ― Benjamin Disraeli",
    "“Music is the moonlight in the gloomy night of life.” ― Jean Paul Friedrich Richter",
    "“There is nothing more to be said or to be done tonight, so hand me over my violin and let us try to forget for half an hour the miserable weather and the still more miserable ways of our fellowmen.” ― Arthur Conan Doyle",
    "“The man that hath no music in himself, Nor is not moved with concord of sweet sounds, Is fit for treasons, stratagems, and spoils; The motions of his spirit are dull as night, And his affections dark as Erebus. Let no such man be trusted. Mark the music.” ― William Shakespeare",
    "“Music, when soft voices die, vibrates in the memory.” ― Percy Bysshe Shelley",
    "“When you play, never mind who listens to you.” ― Robert Schumann",
    "“Music, my rampart and my only one.” ― Edna St. Vincent Millay",
    "“This will be our reply to violence: to make music more intensely, more beautifully, more devotedly than ever before.” ― Leonard Bernstein",
    "“Music is what tell us that the human race is greater than we realize.” ― Napoléon Bonaparte",
    "“If you were music, I would listen to you ceaselessly, and my low spirits would brighten up.” ― Anna Akhmatova",
    "“I would rather write 10,000 notes than a single letter of the alphabet.” ― Ludwig van Beethoven"
];
